theme: leap-day
title: "Personal Portfolio"
author: "Kawa Tea√±o (they/them)"
descrption: "Kawa helps people be thoughtful and creative. Here's how."

collections:
  projects:
    output: true
    permalink: /projects/:path